'''
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''


def evenFibs(n):
    if n == 1:
        return 2
    if n == 2:
        return 8
    if n > 2:
        return (4 * evenFibs(n-1)) + evenFibs(n-2)

def getEvens(limit):
    i = 1
    total = 0
    while evenFibs(i) <= limit:
        total += evenFibs(i)
        i += 1
    return total

print getEvens(4000000)
